### ISSUE TITLE
Allow to pass invite code as parameter

### ISSUE THREAD

**Issue by t2d** [systemli/user-management#117]
It would be great if I could send my friend a link like https://users.example.org/register&v=sadfas and this would already fill out the "invite code" in the register field.
We would also need an option to create the link in a sensible way which doesn't create confusion.

**Comment by graybee** [comment]
Is threre anyone there who can give me an invite code for SYSTEMLI.ORG email. I would be very thankful coz your so kind and generous. My email is Tinbox404-hot@yahoo.com
