### ISSUE TITLE
Create indicator for which unit for qouta limit is used

### ISSUE THREAD

**Issue by xshadow** [systemli/user-management#14]
It would be helpful to know which unit is used for the quota (MB/GB/...)

At the moment it's MB. 

Would be nice if you can provide an indicator.

**Comment by t2d** [comment]
![screenshot from 2018-09-28 10-30-29](https://user-images.githubusercontent.com/1834580/46197304-b4308200-c309-11e8-8f42-ed5722862a0e.png)

very good idea. thank you
