### ISSUE TITLE
Limit password length

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/user-management#2]
In order to mitigate potential DoS attacks, we should limit the maximum length of a password (e.g. to ~160 characters). Computing time for hashes grows with size of the string to be hashed. This is particularely true for PBKDF2: https://www.djangoproject.com/weblog/2013/sep/15/security/

**Comment by t2d** [comment]
Is already solved in `PasswordHashEncoder`:
```
    public function encodePassword($raw, $salt)
    {
        if ($this->isPasswordTooLong($raw)) {
            throw new BadCredentialsException('Invalid password.');
        }
```

```
    const MAX_PASSWORD_LENGTH = 4096;
```
