### ISSUE TITLE
Don't list redeemed vouchers

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/user-management#23]
I don't see a good reason to list redeemed vouchers in the frontend. If we would not list them, we could change the list order back to normal (list oldest ones first).

If we do this, we have to take care that the displayed message in case of no left vouchers is different than the one displayed if no vouchers are created yet.

What do you think?

**Comment by t2d** [comment]
Yes, don’t list them. But still some users could have many unredeemed vouchers

**Comment by doobry-systemli** [comment]
> Yes, don’t list them.

Ok will do so.

> But still some users could have many unredeemed vouchers

That's why I would keep the "create voucher" button on top.
