### ISSUE TITLE
Remove field "destination" from entity Alias

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/user-management#27]
Since we now tie aliases to specific users, we don't need the field `destination` any longer. Fields `user_id` and `destination` are redundant at the moment. Thus, field `destination` should be dropped.

But first, we have to decide what to do about existing one-to-many aliases[1], which we use as "poor mans distributors" at the moment.

[1] Groups of aliases, where same `source` is used several times with different `destination` values.

**Comment by t2d** [comment]
Currently, the table is also accessed directly by Postfix to see if it can deliver an email. The current query for aliases is 
```
query = SELECT destination FROM virtual_aliases WHERE source='%s'
```
So it could be changed to 
```
query = SELECT u.email FROM virtual_users u, virtual_aliases a WHERE a.source='%s' and a.user_id = u.id;
```
Apart from managing this manually, which is obviously not great, I see no further problems.

**Comment by t2d** [comment]
`virtual_alias_maps` is an ["Optional lookup tables that alias specific mail addresses or domains to other local or remote address."](http://www.postfix.org/postconf.5.html#virtual_alias_maps)
If we delete `destination`, we can't do remote forwarding anymore. Which we are not using currently.

**Comment by t2d** [comment]
The option to set remote destinations has already been removed in #22

**Comment by t2d** [comment]
No, we'll keep destination field to allow for custom destinations and will make this available again in the admin interface only.
