### ISSUE TITLE
Allow users to create custom aliases

### ISSUE THREAD

**Issue by t2d** [systemli/user-management#40]
Users should be able to create some aliases for themselves. Maybe we should also require vouchers for that? Or just set a global maximum? Or...?

**Comment by doobry-systemli** [comment]
Regarding limits/requirements for vouchers:

Currently the hard limit for aliases per user is set to 20 in the user frontend (implemented with the randomAliases feature).

In my opinion, that's enough: every user is allowed to create 20 aliases (regardless whether it's custom or random aliases).

**Comment by t2d** [comment]
I would like to allow more random aliases to feed them to online shops, fora, etc. But a more limited amount of custom alias since they fill up our human-readable mail address space. Okay?

**Comment by doobry-systemli** [comment]
Done by merging #41.
