### ISSUE TITLE
Explain purpose of alias addresses

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/user-management#45]
Once the alias management moved to a dedicated subpage, we should explain the purpose of random alias addresses a bit:

Unique mail addresses are used to track users across different places, random alias addresses help to preserve privacy.

**Comment by doobry-systemli** [comment]
Add some description:
* what are custom and random aliases meant for?
* state that mails to them end up in your normal mailbox
* actually mention the main mail address on the alias page ("mails to your aliases will be forwarded to the inbox of your mail account <user>@example.org")

**Comment by t2d** [comment]
![screenshot from 2019-02-20 18-49-08](https://user-images.githubusercontent.com/1834580/53112755-47c85080-3540-11e9-92b7-0fdfe7b2b4e0.png)

**Comment by t2d** [comment]
![screenshot from 2019-02-20 18-48-57](https://user-images.githubusercontent.com/1834580/53112757-47c85080-3540-11e9-822c-c7c869d7911f.png)

**Comment by doobry-systemli** [comment]
I like it that way! Thanks for working on this issue. One minor remark: don't forget to mention the change in the changelog file.

**Comment by doobry-systemli** [comment]
> One minor remark: don't forget to mention the change in the changelog file.

I did this now.
