### ISSUE TITLE
Continous testing for other database backends

### ISSUE THREAD

**Issue by doobry-systemli** [systemli/user-management#55]
We should integrate continuous testing of postgresql (and sqlite3) database backends into our testsuite.

My current idea is to create separate test environments `test-mysql`, `test-pgsql` and `test-sqlite` and run our functional tests in all three environments.

**Comment by 0x46616c6b** [comment]
For this we should use the build matrix in Travis with different ENV variables (`DATABASE_URL`, `DATABASE_DRIVER`). There is no reason to create another Symfony Environments. We should adopt the current variables and make this configurable in the test environment.
