### ISSUE TITLE
updatedTime is updated with every login

### ISSUE THREAD

**Issue by t2d** [systemli/user-management#71]
Every login sets the field `lastlogin` to current time. However, `updateUpdatedTime` is set as lifecycleCallback in  [config/doctrine/User.orm.yml](https://github.com/systemli/user-management/blob/master/config/doctrine/User.orm.yml#L62). Therefore, `updatedTime` is always updated with `lastlogin`. 

Is this okay? I feel like the original idea was to change it only if real attributes change, not a timestamp.

**Comment by t2d** [comment]
I think we should do 2 things:

1. Ignore `lastlogin` in `updateUpdatedTime` https://www.doctrine-project.org/projects/doctrine-orm/en/latest/reference/events.html#lifecycle-events
2. Update `lastlogin` when user logs in in web frontend

**Comment by 0x46616c6b** [comment]
We should avoid using the `lifecycleCallback`. This is kind of magic and we cannot unit test this feature.

**Comment by t2d** [comment]
> 2. Update `lastlogin` when user logs in in web frontend

Already implemented in `LoginListener`
