### ISSUE TITLE
Create Role that is not allowed to send

### ISSUE THREAD

**Issue by t2d** [systemli/user-management#77]
When we implement mailcrypt, we won't be able to change the passwords of users anymore. This would delete all their mails. But if an account is hacked, we need to ensure that is is not continuously used to send SPAM. The easiest way to ensure this, is to deny the account to send mails until the situation has been resolved.

**Comment by 0x46616c6b** [comment]
We can reuse the `ROLE_*` system for that case. So we add for example `ROLE_SPAM` and implement the login that only user which dont have these role can successfully login to the system.

**Comment by doobry-systemli** [comment]
I think, we should have several new roles:

* `ROLE_NOSEND` denies sending of mail but still allows to receive (for spam accounts). Login to user-management should still be possible.
* `ROLE_NORECEIVE` denies receiving of external mail but still allows to send mail (e.g. for accounts which exceed our soft quota). Login to user-management should still be possible.
* `ROLE_DISABLED` completely disables the account (no sending, no receiving, no login) but allows to enable it again later (contrary to accounts with `deleted = true`, where passwords are reset and mailboxes are removed).

What do you think?

Whatever we do (even with your suggestions from above), I'm not sure how to implement this on postfix and dovecot level. `ROLE_DISABLED` would be easy, but for the other two roles we would have to tell postfix to not to allow either sending or receiving. Only solution that comes to my mind is to export a postfix [`access table`](http://www.postfix.org/access.5.html) each and use it in [`smtpd_sender_restrictions`](http://www.postfix.org/postconf.5.html#smtpd_sender_restrictions) and [`smtpd_recipient_restrictions`](http://www.postfix.org/postconf.5.html#smtpd_recipient_restrictions).

That would be a feature which is only supported with postfix as MTA, but I'd be ok with that.

**Comment by t2d** [comment]
* `ROLE_NOSEND` == `ROLE_SPAM`
* I think, `ROLE_NORECEIVE` is a bad idea. Especially to encorce a "soft" quota. This will give strange feedback to other mail providers and start a lot of confusion. I hate, when other providers do this.
* What is the actual use case of `ROLE_DISABLED`?

I had a special problem that I wanted to fix. You proposal sound like a bit of over-engineering to me.

**Comment by doobry-systemli** [comment]
Ok, let's go with `ROLE_SPAM` for now and discuss the rest later.
